name: paperless_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.11+11
publish_to: none

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  edge_detection:
    git:
      url: https://github.com/bauerj/edge_detection
      ref: ec8639fffef3d6d0714b260067f77dd1261b39ed
  cached_network_image: ^3.0.0
  dio: ^4.0.0
  flutter_secure_storage: ^4.1.0
  flutter_svg: ^0.19.3
  get_it: ^6.0.0
  http_auth: ^1.0.0
  i18n_extension: ^4.0.0
  json_annotation: ^4.0.1
  open_file: ^3.1.0
  receive_sharing_intent: ^1.4.5
  settings_ui: ^0.6.0
  shared_preferences: ">=0.5.7+2 <2.0.0"
  wechat_assets_picker: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  archive: ^3.1.2
  build_runner: ^1.12.2
  json_serializable: ^4.1.0

dependency_overrides:
  cached_network_image: any
  flutter_svg: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - logo.svg
    - assets/locales/
  fonts:
    - family: AlegreyaSans
      fonts:
        - asset: assets/fonts/AlegreyaSans-Regular.ttf
        - asset: assets/fonts/AlegreyaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/AlegreyaSans-Bold.ttf
          weight: 700
